feat: oidc4vp bdd tests.
trustbloc/vcs pull request #854
Opened 2022-10-11 06:30 UTC by vkubiv

Signed-off-by: Volodymyr Kubiv <volodymyr.kubiv@euristiq.com>

2022-10-11 12:34 UTC, sudeshrshetty approved these changes

2022-10-11 13:33 UTC, fqutishat requested changes

2022-10-11 13:33 UTC, fqutishat commented on cmd/vc-rest/startcmd/params.go
> +	redisURLFlagName  = "redis-url"
need to remove radis

2022-10-12 10:18 UTC, fqutishat approved these changes

2022-10-12 10:28 UTC, merged