feat: vc token api
trustbloc/vcs pull request #928
Opened 2022-11-01 20:14 UTC by skynet2

feat: vc token api

2022-11-01 20:40 UTC, skynet2 commented
@fqutishat @aholovko 
![image](https://user-images.githubusercontent.com/3065048/199336548-ef3dfac1-f2b0-4008-b8db-122f916083ff.png)
there is such problem, but this is not related to my changes, its related to metrics from Baha, not sure why it shows impact in my pr

2022-11-02 07:51 UTC, aholovko requested changes
Additional changes:
* fix "exchnage" in `pkg/service/oidc4vc/oidc4vc_service_exchnage_code_test.go`
* update `controller_e2e_flows_test.go` "integration" test with additional step for token endpoint

2022-11-02 07:51 UTC, aholovko commented on docs/v1/openapi.yaml
> +      operationId: exchange-authorization-code-request
change "exchange-authorization-code-request" to "exchange-authorization-code" for generated handler to be `ExchangeAuthorizationCode`

2022-11-02 07:51 UTC, aholovko commented on pkg/service/oidc4vc/oidc4vc_service_exchnage_code_test.go
> +	time.Sleep(2 * time.Second)
this doesn't look like a unit test
try to introduce abstraction for `oauthConfig` with its `Exchange` method and use mock

2022-11-02 14:38 UTC, aholovko approved these changes

2022-11-02 15:02 UTC, fqutishat approved these changes

2022-11-02 15:02 UTC, merged