feat: base pre-auth bdd tests
trustbloc/vcs pull request #951
Opened 2022-11-11 20:50 UTC by skynet2

2022-11-14 07:48 UTC, aholovko requested changes

2022-11-14 07:48 UTC, aholovko commented on cmd/vc-rest/startcmd/start.go
> +		InternalHostURL:         getInternalHost(conf.StartupParameters.hostURL),
plz elaborate on the purpose of this parameter

2022-11-14 12:58 UTC, fqutishat commented on cmd/vc-rest/startcmd/params.go
> +	publicAPIURLFlagName      = "public-api-url"
why we need it

2022-11-14 12:58 UTC, fqutishat commented on cmd/vc-rest/startcmd/params.go
> +	issuerAPIURLFlagName      = "issuer-api-url"
why we need it

2022-11-14 19:18 UTC, fqutishat approved these changes

2022-11-15 07:05 UTC, aholovko approved these changes

2022-11-15 07:23 UTC, merged